---
- hosts: all
  become: true
  tasks:
    - user:
        name: "{{ item.name }}"
        uid: "{{ item.uid | int }}"
        password: "{{ item.pwd | password_hash('sha512') }}"  
      with_file:
        - userslist.yml
