---
- hosts: databases
  become: true
  tasks:
  - yum:
      name: 
        - mariadb-server 
        - mariadb
      state: latest
  - systemd:
      name: mariadb
      state: started
      enabled: true
