---
- hosts: databases
  become: true
  tasks:
  - yum:
      name: postgresql
      state: latest
  - shell: cmd="postgresql-setup --initdb"
  - systemd:
      name: postgresql
      state: started
      enabled: true
