---
- hosts: databases
  become: true
  tasks:
  - yum:
      name: 
        - postgresql
        - postgresql-contrib
        - postgresql-server
      state: latest
  - shell: cmd="postgresql-setup initdb"
    environment: 
      PATH: /sbin:/bin:/usr/sbin:/usr/bin
    become_user: postgres
    become: yes
  - systemd:
      name: postgresql
      state: started
      enabled: true
    become_user: root
    become: yes
